name: Expressions & Contexts
on: [push, pull_request, issues, workflow_dispatch]

jobs:
  Test-Expressions-Contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Expessions
        id: experssions
        run: |
          echo ${{ 420 }}
          echo ${{ 'This is a string '}}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String '}}
          echo ${{ true && false }}
          echo ${{ true || (false && true )}}

      - name: Contexts
        run: |
          echo ${{ toJson(github) }}
          echo ${{ toJson(job) }}
          echo ${{ toJson(secrets) }}
          echo ${{ toJson(steps) }}
          echo ${{ toJson(runner) }}
