name: First workflow

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiple line
        run: |
          node -v
          npm -v
  parallel-job:
    runs-on: macos-latest
    steps:
      - name: Check sw version
        run: sw_vers
  dependent-job:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: echo a string in powershell
        run: Write-Output "Windows string"
      - name: Error step
        run: doesnotexistss
