#run job multiple times with different variables
#run job multiple times with different node versions
#run job with each value in array, from scratch in runner machine, treat like different jobs
#matrix for runs-on -> it will run all possible combinations all node versions for each os

name: Matrix Workflow
on: [push]

jobs:
  node-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
