#commenting on pr with pull_request_target event
#use of github script - https://octokit.github.io/rest.js/v20#issues-create-comment

name: Comment on PR
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Commenting on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
              body: 'Thanks for creating PR'
            });
