# status check function failure() -> returns true previous job / step is failed
# if success() -> success() is default behavior
# always() -> return true / always runs step / job regardless of status of previous job / step even if they are skipped
# cancelled() -> returns true if workflow is cancelled, runs step / job when workflow is cancelled

name: Status check

on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Runs on failure
        if: failure()
        run: echo 'runs only on failure'
      - name: Runs on success
        if: success()
        run: echo 'runs on success'
      - name: Always runs
        if: always()
        run: echo 'runs always'
      - name: Runs when cancelled
        if: cancelled()
        run: echo 'runs when cancelled'

  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'job-2 ran'
