name: Workflow Run
on:
  workflow_run:
    workflows: [Events Workflow]
    types: [completed]

jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered based on workflow_run of another workflow completion"
