# Workflow commands - send command to runner machine from within the jobs.
# Example -  Send error message - but job won't fail
# This is to raise custom errors / messages from pipeline to tell to the developers, in Summary we can see that

name: Workflow commands
on: [push]

jobs:
  set-error-debug-warn-notice-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Set simple error message
        run: echo "::error::Missing Semicolon"
      - name: Set parameterized error message
        run: echo "::error title=Parameterized Error,file=app.js,line=1,endLine=1,col=3,endColumn=5::Missing Semicolon Parameterized from job"
      - name: Set debug message
        run: echo "::debug title=Debug Title::This is debug message from job"
      - name: Set warn message
        run: echo "::warning title=Warning Title::This is warning message from job"
      - name: Set notice message
        run: echo "::notice title=Notice Title::This is notice message from job"
  set-group-masked-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Set a group message
        run: |
          echo "::group::My Group Title"
          echo "I am inside the group"
          echo "::endgroup::"
      - name: Set a masked message
        run: echo "::add-mask::SecretMessage"
      - name: Set an unmasked message
        run: echo "SecretMessage"
